/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Apekshya
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        DashBoard = new javax.swing.JPanel();
        DB = new javax.swing.JButton();
        MyBookingButton = new javax.swing.JButton();
        Vehicles = new javax.swing.JButton();
        Profilebutton = new javax.swing.JButton();
        Logoutbutton = new javax.swing.JButton();
        TopPart = new javax.swing.JPanel();
        UserName = new javax.swing.JLabel();
        Pfp = new javax.swing.JLabel();
        BAV = new javax.swing.JLabel();
        DashboardNavi = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        FilterSection = new javax.swing.JPanel();
        Clearbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AllTypesCB = new javax.swing.JCheckBox();
        SuvCB = new javax.swing.JCheckBox();
        SedanCB = new javax.swing.JCheckBox();
        HatchbackCB = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        AllCB = new javax.swing.JCheckBox();
        AutomaticCB = new javax.swing.JCheckBox();
        ManualCB = new javax.swing.JCheckBox();
        SearchBar = new javax.swing.JTextField();
        Sortbybox = new javax.swing.JComboBox<>();
        Cars = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        Car1Panel = new javax.swing.JPanel();
        Select1 = new javax.swing.JButton();
        CarImg1 = new javax.swing.JLabel();
        CarName1 = new javax.swing.JLabel();
        Car1Price = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Car1Stock = new javax.swing.JLabel();
        Car2Panel = new javax.swing.JPanel();
        Select2 = new javax.swing.JButton();
        Car2Img = new javax.swing.JLabel();
        Car2Name = new javax.swing.JLabel();
        Car2Price = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Car2Stock = new javax.swing.JLabel();
        Car3Panel = new javax.swing.JPanel();
        Select3 = new javax.swing.JButton();
        Car3Img = new javax.swing.JLabel();
        Car3Name = new javax.swing.JLabel();
        Car3Price = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Stock3 = new javax.swing.JLabel();
        Logo = new javax.swing.JPanel();
        DVRlogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DashBoard.setBackground(new java.awt.Color(255, 255, 255));

        DB.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        DB.setText("🏠 DashBoard  ");
        DB.setBorderPainted(false);
        DB.addActionListener(this::DBActionPerformed);

        MyBookingButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        MyBookingButton.setText("🗓️ My Bookings");
        MyBookingButton.setBorderPainted(false);
        MyBookingButton.addActionListener(this::MyBookingButtonActionPerformed);

        Vehicles.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Vehicles.setText("🚗 Vehicles      ");
        Vehicles.setBorderPainted(false);

        Profilebutton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Profilebutton.setText("👤 Profile        ");
        Profilebutton.setBorderPainted(false);
        Profilebutton.addActionListener(this::ProfilebuttonActionPerformed);

        Logoutbutton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        Logoutbutton.setText("←] Logout     ");
        Logoutbutton.setBorderPainted(false);

        javax.swing.GroupLayout DashBoardLayout = new javax.swing.GroupLayout(DashBoard);
        DashBoard.setLayout(DashBoardLayout);
        DashBoardLayout.setHorizontalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DB, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(MyBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Vehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Profilebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logoutbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DashBoardLayout.setVerticalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MyBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Vehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TopPart.setBackground(new java.awt.Color(255, 255, 255));

        UserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UserName.setText("User");
        UserName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Pfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/User (2).jpg"))); // NOI18N
        Pfp.setText("jLabel4");

        BAV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BAV.setText("Book a Vehicle");

        DashboardNavi.setText("Dashboard");

        javax.swing.GroupLayout TopPartLayout = new javax.swing.GroupLayout(TopPart);
        TopPart.setLayout(TopPartLayout);
        TopPartLayout.setHorizontalGroup(
            TopPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BAV, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DashboardNavi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
        TopPartLayout.setVerticalGroup(
            TopPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopPartLayout.createSequentialGroup()
                        .addGroup(TopPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pfp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(TopPartLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(BAV, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DashboardNavi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Body.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(238, 237, 237));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        jLabel3.setText("Select Your Vehicle ");

        FilterSection.setBackground(new java.awt.Color(255, 255, 255));

        Clearbutton.setText("Clear Filters");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Filter");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Vehicle Type");

        AllTypesCB.setText("All Types");
        AllTypesCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SuvCB.setText("SUV");
        SuvCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        SedanCB.setText("Sedan");
        SedanCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        HatchbackCB.setText("Hatchback");
        HatchbackCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        HatchbackCB.addActionListener(this::HatchbackCBActionPerformed);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Transmission");

        AllCB.setText("All");
        AllCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AutomaticCB.setText("Automatic");
        AutomaticCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AutomaticCB.addActionListener(this::AutomaticCBActionPerformed);

        ManualCB.setText("Manual");
        ManualCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout FilterSectionLayout = new javax.swing.GroupLayout(FilterSection);
        FilterSection.setLayout(FilterSectionLayout);
        FilterSectionLayout.setHorizontalGroup(
            FilterSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FilterSectionLayout.createSequentialGroup()
                .addGroup(FilterSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AllTypesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SuvCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SedanCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HatchbackCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AllCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AutomaticCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ManualCB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FilterSectionLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        FilterSectionLayout.setVerticalGroup(
            FilterSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FilterSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllTypesCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SuvCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SedanCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HatchbackCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AutomaticCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ManualCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Clearbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        SearchBar.setText("🔍 Search");

        Sortbybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by :", "Recommended", "Price: Low to High", "Price: High to Low", "Ratings" }));

        Cars.setBackground(new java.awt.Color(238, 237, 237));

        Car1Panel.setBackground(new java.awt.Color(255, 255, 255));

        Select1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Select1.setForeground(new java.awt.Color(153, 204, 255));
        Select1.setText("Select");
        Select1.addActionListener(this::Select1ActionPerformed);

        CarImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bmw (2).jpg"))); // NOI18N
        CarImg1.setText("jLabel9");

        CarName1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        CarName1.setText("BMW X5");

        Car1Price.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Car1Price.setText("$80/day");

        jLabel18.setText("⚙️ Automatic");

        jLabel19.setText("💺 5 seats");

        jLabel24.setText("❄️ AC");

        Car1Stock.setBackground(new java.awt.Color(204, 255, 204));
        Car1Stock.setForeground(new java.awt.Color(48, 188, 76));
        Car1Stock.setText("InStock");
        Car1Stock.setOpaque(true);

        javax.swing.GroupLayout Car1PanelLayout = new javax.swing.GroupLayout(Car1Panel);
        Car1Panel.setLayout(Car1PanelLayout);
        Car1PanelLayout.setHorizontalGroup(
            Car1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Car1PanelLayout.createSequentialGroup()
                .addGroup(Car1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Car1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Car1Stock)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Car1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Car1PanelLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Select1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Car1PanelLayout.createSequentialGroup()
                        .addGroup(Car1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CarName1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Car1PanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)))
                        .addGap(18, 18, 18)
                        .addComponent(Car1Price)))
                .addContainerGap())
        );
        Car1PanelLayout.setVerticalGroup(
            Car1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Car1PanelLayout.createSequentialGroup()
                .addGroup(Car1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Car1PanelLayout.createSequentialGroup()
                        .addComponent(CarImg1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Car1Stock)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(Car1PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Car1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Car1PanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Car1Price, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Select1))
                            .addGroup(Car1PanelLayout.createSequentialGroup()
                                .addComponent(CarName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Car1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        Car2Panel.setBackground(new java.awt.Color(255, 255, 255));

        Select2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Select2.setForeground(new java.awt.Color(153, 204, 255));
        Select2.setText("Select");
        Select2.setAutoscrolls(true);

        Car2Img.setIcon(new javax.swing.ImageIcon("C:\\Users\\Apekshya\\Downloads\\mer (1).jpg")); // NOI18N
        Car2Img.setText("jLabel9");

        Car2Name.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        Car2Name.setText("Mercedes-benz G63");

        Car2Price.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Car2Price.setText("75$/day");

        jLabel20.setText("⚙️ Manual");

        jLabel21.setText("💺 5 seats");

        jLabel25.setText("❄️ AC");

        Car2Stock.setBackground(new java.awt.Color(204, 255, 204));
        Car2Stock.setForeground(new java.awt.Color(48, 188, 76));
        Car2Stock.setText("InStock");
        Car2Stock.setOpaque(true);

        javax.swing.GroupLayout Car2PanelLayout = new javax.swing.GroupLayout(Car2Panel);
        Car2Panel.setLayout(Car2PanelLayout);
        Car2PanelLayout.setHorizontalGroup(
            Car2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Car2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Car2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Car2PanelLayout.createSequentialGroup()
                        .addComponent(Car2Img, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Car2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Car2Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Car2PanelLayout.createSequentialGroup()
                                .addGroup(Car2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Car2PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel21))
                                    .addComponent(jLabel25))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Car2Price))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Car2PanelLayout.createSequentialGroup()
                        .addComponent(Car2Stock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Select2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Car2PanelLayout.setVerticalGroup(
            Car2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Car2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Car2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Car2PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Car2Price, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Select2)
                        .addContainerGap())
                    .addGroup(Car2PanelLayout.createSequentialGroup()
                        .addGroup(Car2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Car2PanelLayout.createSequentialGroup()
                                .addComponent(Car2Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Car2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addComponent(Car2Img, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Car2Stock)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );

        Car3Panel.setBackground(new java.awt.Color(255, 255, 255));

        Select3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Select3.setForeground(new java.awt.Color(153, 204, 255));
        Select3.setText("Select");
        Select3.addActionListener(this::Select3ActionPerformed);

        Car3Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pporsche (1).jpg"))); // NOI18N
        Car3Img.setText("jLabel9");

        Car3Name.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        Car3Name.setText("Porsche 911 GT3");

        Car3Price.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Car3Price.setText("100$/day");

        jLabel22.setText("⚙️ Manual");

        jLabel23.setText("💺 4 seats");

        jLabel26.setText("❄️ AC");

        Stock3.setBackground(new java.awt.Color(204, 255, 204));
        Stock3.setForeground(new java.awt.Color(48, 188, 76));
        Stock3.setText("InStock");
        Stock3.setOpaque(true);

        javax.swing.GroupLayout Car3PanelLayout = new javax.swing.GroupLayout(Car3Panel);
        Car3Panel.setLayout(Car3PanelLayout);
        Car3PanelLayout.setHorizontalGroup(
            Car3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Car3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Car3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Car3Img, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Car3PanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Stock3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Car3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Car3Name)
                    .addGroup(Car3PanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23))
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Car3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Car3Price, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Select3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        Car3PanelLayout.setVerticalGroup(
            Car3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Car3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Car3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Car3PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Car3Price, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Select3)
                        .addContainerGap())
                    .addGroup(Car3PanelLayout.createSequentialGroup()
                        .addGroup(Car3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Car3PanelLayout.createSequentialGroup()
                                .addComponent(Car3Img, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Stock3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Car3PanelLayout.createSequentialGroup()
                                .addComponent(Car3Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Car3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)))
                        .addGap(0, 6, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout CarsLayout = new javax.swing.GroupLayout(Cars);
        Cars.setLayout(CarsLayout);
        CarsLayout.setHorizontalGroup(
            CarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CarsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Car1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Car2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Car3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CarsLayout.setVerticalGroup(
            CarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(CarsLayout.createSequentialGroup()
                        .addComponent(Car1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Car2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Car3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FilterSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SearchBar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sortbybox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Cars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FilterSection, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sortbybox, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Logo.setBackground(new java.awt.Color(255, 255, 255));

        DVRlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Gemini_Generated_Image_hyxex8hyxex8hyxe (3) (1).jpg"))); // NOI18N
        DVRlogo.setText("jLabel1");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DVRlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DVRlogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TopPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DashBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DBActionPerformed

    private void MyBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyBookingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyBookingButtonActionPerformed

    private void ProfilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfilebuttonActionPerformed

    private void Select1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Select1ActionPerformed

    private void AutomaticCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutomaticCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutomaticCBActionPerformed

    private void HatchbackCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HatchbackCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HatchbackCBActionPerformed

    private void Select3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Select3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Select3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AllCB;
    private javax.swing.JCheckBox AllTypesCB;
    private javax.swing.JCheckBox AutomaticCB;
    private javax.swing.JLabel BAV;
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Car1Panel;
    private javax.swing.JLabel Car1Price;
    private javax.swing.JLabel Car1Stock;
    private javax.swing.JLabel Car2Img;
    private javax.swing.JLabel Car2Name;
    private javax.swing.JPanel Car2Panel;
    private javax.swing.JLabel Car2Price;
    private javax.swing.JLabel Car2Stock;
    private javax.swing.JLabel Car3Img;
    private javax.swing.JLabel Car3Name;
    private javax.swing.JPanel Car3Panel;
    private javax.swing.JLabel Car3Price;
    private javax.swing.JLabel CarImg1;
    private javax.swing.JLabel CarName1;
    private javax.swing.JPanel Cars;
    private javax.swing.JButton Clearbutton;
    private javax.swing.JButton DB;
    private javax.swing.JLabel DVRlogo;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JLabel DashboardNavi;
    private javax.swing.JPanel FilterSection;
    private javax.swing.JCheckBox HatchbackCB;
    private javax.swing.JPanel Logo;
    private javax.swing.JButton Logoutbutton;
    private javax.swing.JCheckBox ManualCB;
    private javax.swing.JButton MyBookingButton;
    private javax.swing.JLabel Pfp;
    private javax.swing.JButton Profilebutton;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JCheckBox SedanCB;
    private javax.swing.JButton Select1;
    private javax.swing.JButton Select2;
    private javax.swing.JButton Select3;
    private javax.swing.JComboBox<String> Sortbybox;
    private javax.swing.JLabel Stock3;
    private javax.swing.JCheckBox SuvCB;
    private javax.swing.JPanel TopPart;
    private javax.swing.JLabel UserName;
    private javax.swing.JButton Vehicles;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
