package view;
import dao.UserDao_Login;
import javax.swing.JFrame;
import model.UserData_Login;
import view.User_Dashboard;
import view.Signup;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Password_icon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Signup_button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Username_icon = new javax.swing.JLabel();
        Username_Label = new javax.swing.JTextField();
        Password_Label = new javax.swing.JTextField();
        Login_button1 = new javax.swing.JButton();
        ForgotPassword_Button = new javax.swing.JButton();
        jLabel63 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Password_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download__1_-removebg-preview.png"))); // NOI18N
        jPanel1.add(Password_icon);
        Password_icon.setBounds(140, 230, 30, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Welcome Back");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 70, 130, 41);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Dont have an accocunt?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 370, 130, 41);

        Signup_button.setForeground(new java.awt.Color(51, 102, 255));
        Signup_button.setText("Signup");
        Signup_button.addActionListener(this::Signup_buttonActionPerformed);
        jPanel1.add(Signup_button);
        Signup_button.setBounds(280, 380, 70, 20);

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Login to your account and continue your journey with us.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 110, 310, 40);

        Username_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download-removebg-preview.png"))); // NOI18N
        jPanel1.add(Username_icon);
        Username_icon.setBounds(140, 180, 30, 30);

        Username_Label.setText("Username");
        Username_Label.addActionListener(this::Username_LabelActionPerformed);
        jPanel1.add(Username_Label);
        Username_Label.setBounds(190, 180, 180, 30);

        Password_Label.setText("Password");
        jPanel1.add(Password_Label);
        Password_Label.setBounds(190, 230, 180, 30);

        Login_button1.setBackground(new java.awt.Color(51, 102, 255));
        Login_button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Login_button1.setText("Login");
        Login_button1.addActionListener(this::Login_button1ActionPerformed);
        jPanel1.add(Login_button1);
        Login_button1.setBounds(150, 320, 200, 30);

        ForgotPassword_Button.setForeground(new java.awt.Color(51, 102, 255));
        ForgotPassword_Button.setText("Forgot Password?");
        ForgotPassword_Button.addActionListener(this::ForgotPassword_ButtonActionPerformed);
        jPanel1.add(ForgotPassword_Button);
        ForgotPassword_Button.setBounds(240, 280, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(520, 150, 510, 460);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jLabel63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel63);
        jLabel63.setBounds(20, 10, 204, 124);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car og.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1220, 50, 304, 699);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_LabelActionPerformed

    private void Signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_buttonActionPerformed
        // TODO add your handling code here:
    Signup signupFrame = new Signup();
    signupFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
    signupFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Signup_buttonActionPerformed

    private void Login_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_button1ActionPerformed
        // TODO add your handling code here:
          // Get text from YOUR exact UI components
     String username = Username_Label.getText();
    String password = Password_Label.getText();

    if (username.trim().isEmpty() || password.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter both Username and Password.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    UserDao_Login dao = new UserDao_Login();
    UserData_Login loggedUser = dao.authenticateUser(username, password);

    if (loggedUser != null) {
        JOptionPane.showMessageDialog(this, "Welcome back, " + loggedUser.getUsername() + "!", "Login Success", JOptionPane.INFORMATION_MESSAGE);
        User_Dashboard dashboard = new User_Dashboard();
        dashboard.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid Username or Password!", "Login Failed", JOptionPane.ERROR_MESSAGE);
    }
                
    }//GEN-LAST:event_Login_button1ActionPerformed

    private void ForgotPassword_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPassword_ButtonActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this, "Contact admin or check your email to reset password.", "Forgot Password", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_ForgotPassword_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ForgotPassword_Button;
    private javax.swing.JButton Login_button1;
    private javax.swing.JTextField Password_Label;
    private javax.swing.JLabel Password_icon;
    private javax.swing.JButton Signup_button;
    private javax.swing.JTextField Username_Label;
    private javax.swing.JLabel Username_icon;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
