package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class Signup extends javax.swing.JPanel {

    /**
     * Creates new form View
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Username_Label = new javax.swing.JTextField();
        Phone_Label = new javax.swing.JTextField();
        Dob_Label = new javax.swing.JTextField();
        ConfirmPassword_Label = new javax.swing.JTextField();
        Password_Label = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DriverLicense_Label = new javax.swing.JTextField();
        RegistrationButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Address_Label = new javax.swing.JTextField();
        Email_Label = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(239, 239, 239));
        setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Username");
        add(jLabel1);
        jLabel1.setBounds(430, 220, 100, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Phone Number");
        add(jLabel2);
        jLabel2.setBounds(430, 280, 170, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Password");
        add(jLabel3);
        jLabel3.setBounds(430, 350, 90, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText(" Email Address");
        add(jLabel4);
        jLabel4.setBounds(650, 220, 110, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Date Of Birth");
        add(jLabel5);
        jLabel5.setBounds(650, 280, 170, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Confirm Password");
        add(jLabel6);
        jLabel6.setBounds(650, 350, 140, 16);

        Username_Label.addActionListener(this::Username_LabelActionPerformed);
        add(Username_Label);
        Username_Label.setBounds(430, 250, 170, 22);

        Phone_Label.addActionListener(this::Phone_LabelActionPerformed);
        add(Phone_Label);
        Phone_Label.setBounds(430, 310, 170, 22);

        Dob_Label.addActionListener(this::Dob_LabelActionPerformed);
        add(Dob_Label);
        Dob_Label.setBounds(650, 310, 170, 22);
        add(ConfirmPassword_Label);
        ConfirmPassword_Label.setBounds(650, 380, 170, 22);
        add(Password_Label);
        Password_Label.setBounds(430, 380, 170, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Driver's License Number");
        add(jLabel7);
        jLabel7.setBounds(430, 420, 190, 16);

        DriverLicense_Label.addActionListener(this::DriverLicense_LabelActionPerformed);
        add(DriverLicense_Label);
        DriverLicense_Label.setBounds(420, 450, 410, 22);

        RegistrationButton.setText("Register");
        add(RegistrationButton);
        RegistrationButton.setBounds(580, 580, 90, 23);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Address");
        add(jLabel8);
        jLabel8.setBounds(430, 490, 110, 16);
        add(Address_Label);
        Address_Label.setBounds(420, 520, 410, 22);

        Email_Label.addActionListener(this::Email_LabelActionPerformed);
        add(Email_Label);
        Email_Label.setBounds(650, 250, 170, 22);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Create Your Account");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(430, 160, 190, 30);

        jLabel11.setText("Join Driveway and start your journey with us");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel4);
        jPanel4.setBounds(430, 190, 250, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thecarimages.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        add(jLabel9);
        jLabel9.setBounds(860, 150, 330, 517);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jLabel63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jLabel63);
        jLabel63.setBounds(10, 10, 204, 124);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Already have an account?");
        add(jLabel10);
        jLabel10.setBounds(1280, 10, 150, 16);

        LoginButton.setText("Login");
        LoginButton.addActionListener(this::LoginButtonActionPerformed);
        add(LoginButton);
        LoginButton.setBounds(1430, 10, 90, 23);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(410, 140, 800, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void Username_LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username_LabelActionPerformed

    private void Email_LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_LabelActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void Phone_LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone_LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone_LabelActionPerformed

    private void Dob_LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dob_LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dob_LabelActionPerformed

    private void DriverLicense_LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverLicense_LabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DriverLicense_LabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address_Label;
    private javax.swing.JTextField ConfirmPassword_Label;
    private javax.swing.JTextField Dob_Label;
    private javax.swing.JTextField DriverLicense_Label;
    private javax.swing.JTextField Email_Label;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField Password_Label;
    private javax.swing.JTextField Phone_Label;
    private javax.swing.JButton RegistrationButton;
    private javax.swing.JTextField Username_Label;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
