/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Apekshya
 */
public class User_Cancellation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(User_Cancellation.class.getName());

    /**
     * Creates new form Payment
     */
    public User_Cancellation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        TopPart = new javax.swing.JPanel();
        BAV = new javax.swing.JLabel();
        DashboardNavi = new javax.swing.JLabel();
        DashBoard = new javax.swing.JPanel();
        DB = new javax.swing.JButton();
        MyBookingButton = new javax.swing.JButton();
        Vehicles = new javax.swing.JButton();
        Profilebutton = new javax.swing.JButton();
        Logoutbutton = new javax.swing.JButton();
        Body = new javax.swing.JPanel();
        PaymentBody = new javax.swing.JPanel();
        CarPic = new javax.swing.JLabel();
        CarName = new javax.swing.JLabel();
        CarType = new javax.swing.JLabel();
        BookingIDPanel = new javax.swing.JPanel();
        BID_txt = new javax.swing.JLabel();
        BookingID = new javax.swing.JLabel();
        Pickup_Panel = new javax.swing.JPanel();
        PU_txt = new javax.swing.JLabel();
        Pick_Uptxt = new javax.swing.JLabel();
        Pickup_Address = new javax.swing.JLabel();
        Dropoff_Panel = new javax.swing.JPanel();
        DO_txt = new javax.swing.JLabel();
        DropOff_Date = new javax.swing.JLabel();
        Dropoff_Address = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        BookingPanel = new javax.swing.JPanel();
        BS_txt = new javax.swing.JLabel();
        BCar_Img = new javax.swing.JLabel();
        Car_Name = new javax.swing.JLabel();
        Pick_up = new javax.swing.JLabel();
        Drop_off = new javax.swing.JLabel();
        Duration_txt = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        RatePerDaytxt = new javax.swing.JLabel();
        Subtotal_txt = new javax.swing.JLabel();
        TaxandFees_txt = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Total_txt = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Pickup_Location = new javax.swing.JLabel();
        Drop_offLocation = new javax.swing.JLabel();
        RatePerDay = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        TaxAndFees = new javax.swing.JLabel();
        VehicleType = new javax.swing.JLabel();
        Cancellation_Note = new javax.swing.JPanel();
        Cancellation_TXT = new javax.swing.JLabel();
        CancellationN_txt = new javax.swing.JLabel();
        CancellationN2_txt = new javax.swing.JLabel();
        Cancellationicon = new javax.swing.JLabel();
        Duration = new javax.swing.JLabel();
        ReasonPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        RefundingProcess = new javax.swing.JPanel();
        Refund_txt = new javax.swing.JLabel();
        Refund_des_txt = new javax.swing.JLabel();
        RA_panel = new javax.swing.JPanel();
        RA_txt = new javax.swing.JLabel();
        Refund_Amount = new javax.swing.JLabel();
        RA_Img = new javax.swing.JLabel();
        RM_Panel = new javax.swing.JPanel();
        RM_txt = new javax.swing.JLabel();
        Refund_Method = new javax.swing.JLabel();
        RM_IMG = new javax.swing.JLabel();
        ERT_Panel = new javax.swing.JPanel();
        ERT_TXT = new javax.swing.JLabel();
        Est_RefundTime = new javax.swing.JLabel();
        ERT_Img = new javax.swing.JLabel();
        RS_Panel = new javax.swing.JPanel();
        RS_txt = new javax.swing.JLabel();
        Refund_Status = new javax.swing.JLabel();
        RS_Img = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Logo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jLabel63.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(jLabel63)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        getContentPane().add(Logo);
        Logo.setBounds(0, 0, 210, 130);

        TopPart.setBackground(new java.awt.Color(255, 255, 255));

        BAV.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        BAV.setText("Cancel Booking");

        DashboardNavi.setText("Dashboard > My booking >  Booking Detail > Cancel Booking");

        javax.swing.GroupLayout TopPartLayout = new javax.swing.GroupLayout(TopPart);
        TopPart.setLayout(TopPartLayout);
        TopPartLayout.setHorizontalGroup(
            TopPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPartLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TopPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DashboardNavi, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAV, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(789, Short.MAX_VALUE))
        );
        TopPartLayout.setVerticalGroup(
            TopPartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BAV, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(DashboardNavi)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(TopPart);
        TopPart.setBounds(218, 0, 1290, 120);

        DashBoard.setBackground(new java.awt.Color(255, 255, 255));

        DB.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        DB.setText("🏠 DashBoard  ");
        DB.setBorderPainted(false);
        DB.addActionListener(this::DBActionPerformed);

        MyBookingButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        MyBookingButton.setText("🗓️ My Bookings");
        MyBookingButton.setBorderPainted(false);
        MyBookingButton.addActionListener(this::MyBookingButtonActionPerformed);

        Vehicles.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Vehicles.setText("🚗 Vehicles      ");
        Vehicles.setBorderPainted(false);
        Vehicles.addActionListener(this::VehiclesActionPerformed);

        Profilebutton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Profilebutton.setForeground(new java.awt.Color(51, 102, 255));
        Profilebutton.setText("👤 Profile        ");
        Profilebutton.setBorderPainted(false);
        Profilebutton.addActionListener(this::ProfilebuttonActionPerformed);

        Logoutbutton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Logoutbutton.setText("←] Logout     ");
        Logoutbutton.setBorderPainted(false);

        javax.swing.GroupLayout DashBoardLayout = new javax.swing.GroupLayout(DashBoard);
        DashBoard.setLayout(DashBoardLayout);
        DashBoardLayout.setHorizontalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashBoardLayout.createSequentialGroup()
                        .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DashBoardLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Vehicles)
                                    .addComponent(Profilebutton)))
                            .addGroup(DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(MyBookingButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashBoardLayout.createSequentialGroup()
                        .addComponent(Logoutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        DashBoardLayout.setVerticalGroup(
            DashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MyBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Vehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addComponent(Logoutbutton)
                .addGap(50, 50, 50))
        );

        getContentPane().add(DashBoard);
        DashBoard.setBounds(0, 131, 210, 640);

        Body.setBackground(new java.awt.Color(255, 255, 255));
        Body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Body.setForeground(new java.awt.Color(153, 0, 0));

        PaymentBody.setBackground(new java.awt.Color(255, 255, 255));
        PaymentBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        CarPic.setText("jLabel1");

        CarName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CarName.setText("BMW X5");

        CarType.setBackground(new java.awt.Color(204, 204, 204));
        CarType.setText("SUV");
        CarType.setOpaque(true);

        BookingIDPanel.setBackground(new java.awt.Color(255, 255, 255));

        BID_txt.setForeground(new java.awt.Color(153, 153, 153));
        BID_txt.setText("Booking ID");

        BookingID.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        BookingID.setText("#BK123456");

        javax.swing.GroupLayout BookingIDPanelLayout = new javax.swing.GroupLayout(BookingIDPanel);
        BookingIDPanel.setLayout(BookingIDPanelLayout);
        BookingIDPanelLayout.setHorizontalGroup(
            BookingIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingIDPanelLayout.createSequentialGroup()
                .addGroup(BookingIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookingID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        BookingIDPanelLayout.setVerticalGroup(
            BookingIDPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingIDPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BID_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BookingID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        Pickup_Panel.setBackground(new java.awt.Color(255, 255, 255));

        PU_txt.setForeground(new java.awt.Color(153, 153, 153));
        PU_txt.setText("Pick-up");

        Pick_Uptxt.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        Pick_Uptxt.setText("📅 20 May 2026, 10:00 AM");

        Pickup_Address.setText("Downtown Branch");

        javax.swing.GroupLayout Pickup_PanelLayout = new javax.swing.GroupLayout(Pickup_Panel);
        Pickup_Panel.setLayout(Pickup_PanelLayout);
        Pickup_PanelLayout.setHorizontalGroup(
            Pickup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pickup_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pickup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PU_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pick_Uptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pickup_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        Pickup_PanelLayout.setVerticalGroup(
            Pickup_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pickup_PanelLayout.createSequentialGroup()
                .addComponent(PU_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pick_Uptxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pickup_Address))
        );

        Dropoff_Panel.setBackground(new java.awt.Color(255, 255, 255));

        DO_txt.setForeground(new java.awt.Color(153, 153, 153));
        DO_txt.setText("Drop-off");

        DropOff_Date.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        DropOff_Date.setText("📅 24 May 2026, 10:00 am");

        Dropoff_Address.setText("Downtown Branch");

        javax.swing.GroupLayout Dropoff_PanelLayout = new javax.swing.GroupLayout(Dropoff_Panel);
        Dropoff_Panel.setLayout(Dropoff_PanelLayout);
        Dropoff_PanelLayout.setHorizontalGroup(
            Dropoff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dropoff_PanelLayout.createSequentialGroup()
                .addGroup(Dropoff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DO_txt)
                    .addComponent(DropOff_Date)
                    .addComponent(Dropoff_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        Dropoff_PanelLayout.setVerticalGroup(
            Dropoff_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dropoff_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DO_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DropOff_Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dropoff_Address)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(227, 227, 227));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(227, 227, 227));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PaymentBodyLayout = new javax.swing.GroupLayout(PaymentBody);
        PaymentBody.setLayout(PaymentBodyLayout);
        PaymentBodyLayout.setHorizontalGroup(
            PaymentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CarPic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PaymentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentBodyLayout.createSequentialGroup()
                        .addComponent(CarName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CarType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PaymentBodyLayout.createSequentialGroup()
                        .addComponent(BookingIDPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Pickup_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dropoff_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
        );
        PaymentBodyLayout.setVerticalGroup(
            PaymentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaymentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentBodyLayout.createSequentialGroup()
                        .addGroup(PaymentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CarName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarType))
                        .addGap(18, 18, 18)
                        .addGroup(PaymentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PaymentBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Pickup_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BookingIDPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Dropoff_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CarPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BookingPanel.setBackground(new java.awt.Color(255, 255, 255));
        BookingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        BS_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BS_txt.setText("Booking Summary");

        BCar_Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bmw (2).jpg"))); // NOI18N
        BCar_Img.setText("jLabel8");

        Car_Name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Car_Name.setText("BMW X5");

        Pick_up.setText("Pick-up");

        Drop_off.setText("Drop-off");

        Duration_txt.setText("Duration");

        RatePerDaytxt.setText("Rate per day");

        Subtotal_txt.setText("Subtotal");

        TaxandFees_txt.setText("Tax & Fees");

        Total_txt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Total_txt.setText("Total");

        Total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total.setText("$0.00");

        Pickup_Location.setBackground(new java.awt.Color(0, 0, 255));
        Pickup_Location.setForeground(new java.awt.Color(0, 0, 204));
        Pickup_Location.setText("Not selected");

        Drop_offLocation.setForeground(new java.awt.Color(0, 0, 255));
        Drop_offLocation.setText("Not selected");

        RatePerDay.setText("$0.00");

        SubTotal.setText("$0.00");

        TaxAndFees.setText("$0.00");

        VehicleType.setBackground(new java.awt.Color(204, 204, 204));
        VehicleType.setText("SUV");
        VehicleType.setOpaque(true);

        Cancellation_Note.setBackground(new java.awt.Color(252, 217, 217));

        Cancellation_TXT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cancellation_TXT.setForeground(new java.awt.Color(153, 0, 0));
        Cancellation_TXT.setText("Cancellation Note");

        CancellationN_txt.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        CancellationN_txt.setForeground(new java.awt.Color(153, 0, 0));
        CancellationN_txt.setText("Your booking will be cancelled only after you confirm.");

        CancellationN2_txt.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        CancellationN2_txt.setForeground(new java.awt.Color(153, 0, 0));
        CancellationN2_txt.setText(" This action cannot be undone.");

        Cancellationicon.setForeground(new java.awt.Color(153, 0, 0));
        Cancellationicon.setText("🛈︎");

        javax.swing.GroupLayout Cancellation_NoteLayout = new javax.swing.GroupLayout(Cancellation_Note);
        Cancellation_Note.setLayout(Cancellation_NoteLayout);
        Cancellation_NoteLayout.setHorizontalGroup(
            Cancellation_NoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cancellation_NoteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cancellation_NoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cancellation_NoteLayout.createSequentialGroup()
                        .addGroup(Cancellation_NoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CancellationN2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Cancellation_NoteLayout.createSequentialGroup()
                                .addComponent(Cancellationicon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cancellation_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(CancellationN_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Cancellation_NoteLayout.setVerticalGroup(
            Cancellation_NoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cancellation_NoteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cancellation_NoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancellation_TXT)
                    .addComponent(Cancellationicon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancellationN_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancellationN2_txt)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Duration.setText("______");

        javax.swing.GroupLayout BookingPanelLayout = new javax.swing.GroupLayout(BookingPanel);
        BookingPanel.setLayout(BookingPanelLayout);
        BookingPanelLayout.setHorizontalGroup(
            BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(BookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingPanelLayout.createSequentialGroup()
                        .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BS_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pick_up)
                            .addComponent(Drop_off)
                            .addComponent(Duration_txt)
                            .addComponent(RatePerDaytxt)
                            .addComponent(Subtotal_txt)
                            .addComponent(TaxandFees_txt)
                            .addComponent(Total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Drop_offLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(Pickup_Location, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookingPanelLayout.createSequentialGroup()
                                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SubTotal)
                                    .addComponent(RatePerDay)
                                    .addComponent(TaxAndFees))
                                .addGap(13, 13, 13))
                            .addComponent(Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Duration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(BookingPanelLayout.createSequentialGroup()
                        .addComponent(BCar_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Car_Name)
                            .addComponent(VehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Cancellation_Note, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BookingPanelLayout.setVerticalGroup(
            BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BS_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BCar_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VehicleType))
                    .addComponent(Car_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pick_up)
                    .addComponent(Pickup_Location))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drop_off)
                    .addComponent(Drop_offLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Duration_txt)
                    .addComponent(Duration))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RatePerDaytxt)
                    .addComponent(RatePerDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subtotal_txt)
                    .addComponent(SubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaxandFees_txt)
                    .addComponent(TaxAndFees, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BookingPanelLayout.createSequentialGroup()
                        .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addComponent(Cancellation_Note, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ReasonPanel.setBackground(new java.awt.Color(255, 255, 255));
        ReasonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("Why are you cancelling this booking?");

        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Please let us know the reason for cancellation");

        jPanel8.setBackground(new java.awt.Color(235, 243, 243));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setText("Cancellation Policy");

        jLabel38.setText("Cancellations made more than 24-hour before pick-up  will be a full refund.");

        jLabel39.setText("Cancellations made within 24 hours of pick-up are non- refundable.");

        jLabel40.setText("Refunds will be processed within 3.5 business days.");

        jLabel53.setText("jLabel49");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jCheckBox1.setText("I understand the cancellation policy and want to cancel this booking");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);

        jRadioButton1.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton1.setText("Change of Plans");

        jRadioButton2.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton2.setText("Found a better price");

        jRadioButton3.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton3.setText("Personal reasons");

        jRadioButton4.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton4.setText("Vehicle not required anymore");

        jRadioButton5.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton5.setText("Pricing Issues");

        jRadioButton6.setForeground(new java.awt.Color(153, 153, 153));
        jRadioButton6.setText("Other");

        javax.swing.GroupLayout ReasonPanelLayout = new javax.swing.GroupLayout(ReasonPanel);
        ReasonPanel.setLayout(ReasonPanelLayout);
        ReasonPanelLayout.setHorizontalGroup(
            ReasonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReasonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReasonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReasonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ReasonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        ReasonPanelLayout.setVerticalGroup(
            ReasonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReasonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(15, 15, 15))
            .addGroup(ReasonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        RefundingProcess.setBackground(new java.awt.Color(255, 255, 255));
        RefundingProcess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Refund_txt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Refund_txt.setText("Refunding Process");

        Refund_des_txt.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Refund_des_txt.setForeground(new java.awt.Color(153, 153, 153));
        Refund_des_txt.setText("Once you confirm the cancellation, your refund will be initiated automatically");

        RA_panel.setBackground(new java.awt.Color(255, 255, 255));

        RA_txt.setForeground(new java.awt.Color(153, 153, 153));
        RA_txt.setText("Refund Amount");

        Refund_Amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Refund_Amount.setText("$00.00");

        RA_Img.setText("jLabel49");

        javax.swing.GroupLayout RA_panelLayout = new javax.swing.GroupLayout(RA_panel);
        RA_panel.setLayout(RA_panelLayout);
        RA_panelLayout.setHorizontalGroup(
            RA_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RA_panelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(RA_Img, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RA_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Refund_Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RA_txt))
                .addGap(18, 18, 18))
        );
        RA_panelLayout.setVerticalGroup(
            RA_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RA_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RA_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RA_txt)
                    .addComponent(RA_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(Refund_Amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        RM_Panel.setBackground(new java.awt.Color(255, 255, 255));

        RM_txt.setForeground(new java.awt.Color(153, 153, 153));
        RM_txt.setText("Refund Method");

        Refund_Method.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Refund_Method.setText("CreditCard (**** ***)");

        RM_IMG.setText("jLabel49");

        javax.swing.GroupLayout RM_PanelLayout = new javax.swing.GroupLayout(RM_Panel);
        RM_Panel.setLayout(RM_PanelLayout);
        RM_PanelLayout.setHorizontalGroup(
            RM_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RM_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RM_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RM_PanelLayout.createSequentialGroup()
                        .addComponent(RM_IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RM_txt)
                        .addGap(18, 18, 18))
                    .addGroup(RM_PanelLayout.createSequentialGroup()
                        .addComponent(Refund_Method)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        RM_PanelLayout.setVerticalGroup(
            RM_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RM_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RM_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RM_txt)
                    .addComponent(RM_IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refund_Method, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ERT_Panel.setBackground(new java.awt.Color(255, 255, 255));

        ERT_TXT.setForeground(new java.awt.Color(153, 153, 153));
        ERT_TXT.setText("Estimated Refund Time");

        Est_RefundTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Est_RefundTime.setText("3-5 Business Days");

        ERT_Img.setText("jLabel51");

        javax.swing.GroupLayout ERT_PanelLayout = new javax.swing.GroupLayout(ERT_Panel);
        ERT_Panel.setLayout(ERT_PanelLayout);
        ERT_PanelLayout.setHorizontalGroup(
            ERT_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ERT_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ERT_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ERT_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Est_RefundTime, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ERT_TXT))
                .addContainerGap())
        );
        ERT_PanelLayout.setVerticalGroup(
            ERT_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ERT_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ERT_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ERT_TXT)
                    .addComponent(ERT_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Est_RefundTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RS_Panel.setBackground(new java.awt.Color(255, 255, 255));

        RS_txt.setForeground(new java.awt.Color(153, 153, 153));
        RS_txt.setText("Refund Status");

        Refund_Status.setBackground(new java.awt.Color(204, 255, 255));
        Refund_Status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Refund_Status.setForeground(new java.awt.Color(64, 139, 255));
        Refund_Status.setText("To be initiated");
        Refund_Status.setOpaque(true);

        RS_Img.setText("jLabel49");

        javax.swing.GroupLayout RS_PanelLayout = new javax.swing.GroupLayout(RS_Panel);
        RS_Panel.setLayout(RS_PanelLayout);
        RS_PanelLayout.setHorizontalGroup(
            RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RS_PanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(RS_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RS_PanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Refund_Status))
                    .addComponent(RS_txt))
                .addGap(11, 11, 11))
        );
        RS_PanelLayout.setVerticalGroup(
            RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RS_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RS_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RS_txt)
                    .addComponent(RS_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Refund_Status)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RefundingProcessLayout = new javax.swing.GroupLayout(RefundingProcess);
        RefundingProcess.setLayout(RefundingProcessLayout);
        RefundingProcessLayout.setHorizontalGroup(
            RefundingProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RefundingProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RefundingProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RefundingProcessLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(RA_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RM_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ERT_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RS_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Refund_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refund_des_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RefundingProcessLayout.setVerticalGroup(
            RefundingProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RefundingProcessLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Refund_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refund_des_txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RefundingProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RS_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RA_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RM_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ERT_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        BackButton.setText("← Back");
        BackButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        BackButton.addActionListener(this::BackButtonActionPerformed);

        ConfirmButton.setBackground(new java.awt.Color(204, 0, 0));
        ConfirmButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmButton.setText("Confirm Cancellation");

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RefundingProcess, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BodyLayout.createSequentialGroup()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ReasonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PaymentBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BodyLayout.createSequentialGroup()
                        .addComponent(PaymentBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReasonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RefundingProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BookingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        getContentPane().add(Body);
        Body.setBounds(220, 130, 1290, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DBActionPerformed

    private void MyBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyBookingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyBookingButtonActionPerformed

    private void VehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehiclesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehiclesActionPerformed

    private void ProfilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfilebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new User_Cancellation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BAV;
    private javax.swing.JLabel BCar_Img;
    private javax.swing.JLabel BID_txt;
    private javax.swing.JLabel BS_txt;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Body;
    private javax.swing.JLabel BookingID;
    private javax.swing.JPanel BookingIDPanel;
    private javax.swing.JPanel BookingPanel;
    private javax.swing.JLabel CancellationN2_txt;
    private javax.swing.JLabel CancellationN_txt;
    private javax.swing.JPanel Cancellation_Note;
    private javax.swing.JLabel Cancellation_TXT;
    private javax.swing.JLabel Cancellationicon;
    private javax.swing.JLabel CarName;
    private javax.swing.JLabel CarPic;
    private javax.swing.JLabel CarType;
    private javax.swing.JLabel Car_Name;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JButton DB;
    private javax.swing.JLabel DO_txt;
    private javax.swing.JPanel DashBoard;
    private javax.swing.JLabel DashboardNavi;
    private javax.swing.JLabel DropOff_Date;
    private javax.swing.JLabel Drop_off;
    private javax.swing.JLabel Drop_offLocation;
    private javax.swing.JLabel Dropoff_Address;
    private javax.swing.JPanel Dropoff_Panel;
    private javax.swing.JLabel Duration;
    private javax.swing.JLabel Duration_txt;
    private javax.swing.JLabel ERT_Img;
    private javax.swing.JPanel ERT_Panel;
    private javax.swing.JLabel ERT_TXT;
    private javax.swing.JLabel Est_RefundTime;
    private javax.swing.JPanel Logo;
    private javax.swing.JButton Logoutbutton;
    private javax.swing.JButton MyBookingButton;
    private javax.swing.JLabel PU_txt;
    private javax.swing.JPanel PaymentBody;
    private javax.swing.JLabel Pick_Uptxt;
    private javax.swing.JLabel Pick_up;
    private javax.swing.JLabel Pickup_Address;
    private javax.swing.JLabel Pickup_Location;
    private javax.swing.JPanel Pickup_Panel;
    private javax.swing.JButton Profilebutton;
    private javax.swing.JLabel RA_Img;
    private javax.swing.JPanel RA_panel;
    private javax.swing.JLabel RA_txt;
    private javax.swing.JLabel RM_IMG;
    private javax.swing.JPanel RM_Panel;
    private javax.swing.JLabel RM_txt;
    private javax.swing.JLabel RS_Img;
    private javax.swing.JPanel RS_Panel;
    private javax.swing.JLabel RS_txt;
    private javax.swing.JLabel RatePerDay;
    private javax.swing.JLabel RatePerDaytxt;
    private javax.swing.JPanel ReasonPanel;
    private javax.swing.JLabel Refund_Amount;
    private javax.swing.JLabel Refund_Method;
    private javax.swing.JLabel Refund_Status;
    private javax.swing.JLabel Refund_des_txt;
    private javax.swing.JLabel Refund_txt;
    private javax.swing.JPanel RefundingProcess;
    private javax.swing.JLabel SubTotal;
    private javax.swing.JLabel Subtotal_txt;
    private javax.swing.JLabel TaxAndFees;
    private javax.swing.JLabel TaxandFees_txt;
    private javax.swing.JPanel TopPart;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Total_txt;
    private javax.swing.JLabel VehicleType;
    private javax.swing.JButton Vehicles;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
