/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Acer
 */
public class user_booking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(user_booking.class.getName());

    /**
     * Creates new form Agent_Vehicles
     */
    public user_booking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        CancelBooking_Button = new javax.swing.JButton();
        LeaveFeedback_Button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        DB = new javax.swing.JButton();
        MyBookingButton = new javax.swing.JButton();
        Vehicles = new javax.swing.JButton();
        Profilebutton = new javax.swing.JButton();
        Logoutbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(2550, 1440));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 153));
        jPanel2.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Gemini_Generated_Image_hyxex8hyxex8hyxe (3) (1).jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 210, 130);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Booking Details");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(210, 0, 274, 58);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("My Bookings  >");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(300, 50, 101, 29);

        jLabel64.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel64.setText("Dashboard  >");
        jPanel2.add(jLabel64);
        jLabel64.setBounds(210, 50, 90, 29);

        jLabel65.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel65.setText("Booking details  ");
        jPanel2.add(jLabel65);
        jLabel65.setBounds(410, 50, 120, 29);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("BMW  X5");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(250, 30, 110, 32);

        jLabel16.setBackground(new java.awt.Color(153, 204, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(39, 75, 146));
        jLabel16.setText("SUV");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(370, 30, 40, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("$320.00");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(650, 120, 100, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/upcoming.png"))); // NOI18N
        jLabel6.setText("#BK1234567");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(460, 120, 100, 30);

        jLabel7.setText("Booking ID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 100, 100, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("#BK1234567");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(260, 120, 100, 30);

        jLabel9.setText("Status");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(470, 90, 100, 30);

        jLabel10.setText("Total Amount");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(650, 90, 100, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(410, 60, 20, 90);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(600, 60, 20, 90);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bmw x5.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 30, 200, 0);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(210, 80, 880, 170);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bmw x5.png"))); // NOI18N
        jPanel3.add(jLabel12);
        jLabel12.setBounds(30, 80, 200, 0);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Booking Summary");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(30, 20, 170, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("BMW  X5");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(240, 70, 70, 20);

        jLabel17.setBackground(new java.awt.Color(153, 204, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(39, 75, 146));
        jLabel17.setText("SUV");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(240, 100, 40, 16);

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel18.setText("24 May 2024, 10:00 AM");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(210, 250, 170, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel19.setText("Pick-off");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(40, 220, 70, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel20.setText("Drop-off");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(40, 250, 80, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel21.setText("$0.00");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(jLabel21);
        jLabel21.setBounds(300, 400, 80, 30);

        jLabel22.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel22.setText("20 May 2024, 10:00 AM");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(210, 220, 170, 30);

        jLabel23.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/info.png"))); // NOI18N
        jLabel23.setText("Taxes and fees");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel3.add(jLabel23);
        jLabel23.setBounds(40, 400, 140, 30);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(30, 320, 380, 20);

        jLabel24.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel24.setText("Duration");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(40, 280, 80, 30);

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel25.setText("Rate Per-day");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(40, 330, 110, 30);

        jLabel26.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel26.setText("Total");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(40, 456, 80, 20);

        jLabel27.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel27.setText("4 Days");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(jLabel27);
        jLabel27.setBounds(300, 280, 70, 30);

        jLabel28.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel28.setText("$80.00");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(jLabel28);
        jLabel28.setBounds(300, 330, 70, 30);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setText("$320.00");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(jLabel29);
        jLabel29.setBounds(290, 460, 70, 20);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(30, 440, 390, 20);

        jLabel30.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel30.setText("Sub-Total");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(40, 370, 110, 30);

        jLabel31.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel31.setText("$320.00");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(jLabel31);
        jLabel31.setBounds(300, 370, 80, 30);

        CancelBooking_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2026-06-10 115718.png"))); // NOI18N
        CancelBooking_Button.setText("jButton1");
        CancelBooking_Button.addActionListener(this::CancelBooking_ButtonActionPerformed);
        jPanel3.add(CancelBooking_Button);
        CancelBooking_Button.setBounds(30, 510, 300, 40);

        LeaveFeedback_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Screenshot 2026-06-10 115737.png"))); // NOI18N
        LeaveFeedback_Button.setText("jButton1");
        jPanel3.add(LeaveFeedback_Button);
        LeaveFeedback_Button.setBounds(30, 560, 310, 40);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(1100, 120, 370, 640);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setText("Trip Details");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(20, 10, 110, 20);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator5);
        jSeparator5.setBounds(440, 30, 10, 150);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/location1.png"))); // NOI18N
        jPanel4.add(jLabel34);
        jLabel34.setBounds(20, 120, 43, 50);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/location1.png"))); // NOI18N
        jPanel4.add(jLabel35);
        jLabel35.setBounds(20, 40, 43, 50);

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("20 May 2026, 10:00 AM");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(70, 70, 140, 16);

        jLabel36.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel36.setText("New York, NY 10001");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(70, 160, 160, 16);

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Pick-Up");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(70, 50, 50, 16);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setText("Downtown Branch");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(70, 120, 120, 16);

        jLabel39.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel39.setText("123 Main Street, Downtown");
        jPanel4.add(jLabel39);
        jLabel39.setBounds(70, 140, 160, 16);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Drop-off");
        jPanel4.add(jLabel40);
        jLabel40.setBounds(580, 50, 60, 16);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setText("20 May 2026, 10:00 AM");
        jPanel4.add(jLabel41);
        jLabel41.setBounds(580, 70, 140, 16);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel42.setText("Downtown Branch");
        jPanel4.add(jLabel42);
        jLabel42.setBounds(580, 120, 120, 16);

        jLabel43.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel43.setText("123 Main Street, Downtown");
        jPanel4.add(jLabel43);
        jLabel43.setBounds(580, 140, 160, 16);

        jLabel44.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel44.setText("New York, NY 10001");
        jPanel4.add(jLabel44);
        jLabel44.setBounds(580, 160, 160, 16);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/location1.png"))); // NOI18N
        jPanel4.add(jLabel45);
        jLabel45.setBounds(510, 40, 43, 50);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/location1.png"))); // NOI18N
        jPanel4.add(jLabel46);
        jLabel46.setBounds(510, 120, 43, 50);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/left-right-arrow.png"))); // NOI18N
        jPanel4.add(jLabel47);
        jLabel47.setBounds(420, 80, 50, 50);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(210, 260, 880, 190);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel48.setText("Vehicle and Rental Details");
        jPanel5.add(jLabel48);
        jLabel48.setBounds(20, 20, 190, 20);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel49.setText("Automatic");
        jPanel5.add(jLabel49);
        jLabel49.setBounds(110, 90, 80, 16);

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText("Yes");
        jPanel5.add(jLabel50);
        jLabel50.setBounds(610, 90, 100, 16);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel51.setText("Petrol");
        jPanel5.add(jLabel51);
        jLabel51.setBounds(110, 160, 80, 16);

        jLabel52.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel52.setText("Air-Conditioning");
        jPanel5.add(jLabel52);
        jLabel52.setBounds(610, 56, 120, 30);

        jLabel53.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel53.setText("Seating Capacity");
        jPanel5.add(jLabel53);
        jLabel53.setBounds(360, 60, 130, 30);

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setText("5 seats");
        jPanel5.add(jLabel54);
        jLabel54.setBounds(360, 90, 100, 16);

        jLabel55.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel55.setText("Transmission");
        jPanel5.add(jLabel55);
        jLabel55.setBounds(100, 56, 90, 30);

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel56.setText("15 Km/L");
        jPanel5.add(jLabel56);
        jLabel56.setBounds(360, 160, 80, 16);

        jLabel57.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel57.setText("Fuel Type");
        jPanel5.add(jLabel57);
        jLabel57.setBounds(100, 130, 80, 30);

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setText("Medium");
        jPanel5.add(jLabel58);
        jLabel58.setBounds(610, 160, 100, 16);

        jLabel59.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel59.setText("Mileage Limit");
        jPanel5.add(jLabel59);
        jLabel59.setBounds(360, 130, 110, 30);

        jLabel60.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel60.setText("Luggage Capacity");
        jPanel5.add(jLabel60);
        jLabel60.setBounds(610, 130, 140, 30);

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/usage.png"))); // NOI18N
        jPanel5.add(jLabel73);
        jLabel73.setBounds(310, 140, 43, 40);

        jLabel74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/automatic-transmission.png"))); // NOI18N
        jPanel5.add(jLabel74);
        jLabel74.setBounds(50, 60, 0, 40);

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/gas-station.png"))); // NOI18N
        jPanel5.add(jLabel75);
        jLabel75.setBounds(50, 140, 43, 40);

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/suitcase.png"))); // NOI18N
        jPanel5.add(jLabel76);
        jLabel76.setBounds(560, 140, 43, 40);

        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/seat.png"))); // NOI18N
        jPanel5.add(jLabel77);
        jLabel77.setBounds(310, 60, 43, 40);

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/car-ac.png"))); // NOI18N
        jPanel5.add(jLabel78);
        jLabel78.setBounds(560, 60, 43, 40);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(210, 460, 880, 180);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel61.setText("18 May 2026, 11:30 AM");
        jPanel6.add(jLabel61);
        jLabel61.setBounds(200, 90, 160, 18);

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel62.setText("Payment Details");
        jPanel6.add(jLabel62);
        jLabel62.setBounds(20, 10, 120, 30);

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel63.setText("#Tk12345678");
        jPanel6.add(jLabel63);
        jLabel63.setBounds(420, 90, 100, 18);

        jLabel66.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel66.setText("Payment Method");
        jPanel6.add(jLabel66);
        jLabel66.setBounds(20, 60, 120, 30);

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel67.setText("Credit Card");
        jPanel6.add(jLabel67);
        jLabel67.setBounds(30, 90, 100, 18);

        jLabel68.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel68.setText("Payment Date");
        jPanel6.add(jLabel68);
        jLabel68.setBounds(200, 60, 100, 30);

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel69.setText("$320.00");
        jPanel6.add(jLabel69);
        jLabel69.setBounds(730, 90, 100, 18);

        jLabel70.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel70.setText("Transaction ID");
        jPanel6.add(jLabel70);
        jLabel70.setBounds(420, 60, 100, 30);

        jLabel71.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel71.setText("Total Amount");
        jPanel6.add(jLabel71);
        jLabel71.setBounds(730, 60, 100, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(210, 650, 880, 120);

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        jLabel72.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jLabel72);
        jLabel72.setBounds(0, 0, 204, 124);

        DB.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        DB.setText("🏠 DashBoard  ");
        DB.setBorderPainted(false);
        DB.addActionListener(this::DBActionPerformed);
        jPanel2.add(DB);
        DB.setBounds(10, 140, 157, 28);

        MyBookingButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        MyBookingButton.setText("🗓️ My Bookings");
        MyBookingButton.setBorderPainted(false);
        MyBookingButton.addActionListener(this::MyBookingButtonActionPerformed);
        jPanel2.add(MyBookingButton);
        MyBookingButton.setBounds(10, 180, 164, 28);

        Vehicles.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Vehicles.setText("🚗 Vehicles      ");
        Vehicles.setBorderPainted(false);
        Vehicles.addActionListener(this::VehiclesActionPerformed);
        jPanel2.add(Vehicles);
        Vehicles.setBounds(10, 220, 153, 28);

        Profilebutton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Profilebutton.setForeground(new java.awt.Color(51, 102, 255));
        Profilebutton.setText("👤 Profile        ");
        Profilebutton.setBorderPainted(false);
        Profilebutton.addActionListener(this::ProfilebuttonActionPerformed);
        jPanel2.add(Profilebutton);
        Profilebutton.setBounds(10, 260, 150, 28);

        Logoutbutton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        Logoutbutton.setText("←] Logout     ");
        Logoutbutton.setBorderPainted(false);
        Logoutbutton.addActionListener(this::LogoutbuttonActionPerformed);
        jPanel2.add(Logoutbutton);
        Logoutbutton.setBounds(30, 740, 138, 28);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1710, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DBActionPerformed

    private void MyBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyBookingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MyBookingButtonActionPerformed

    private void VehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehiclesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VehiclesActionPerformed

    private void ProfilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfilebuttonActionPerformed

    private void LogoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutbuttonActionPerformed

    private void CancelBooking_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBooking_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelBooking_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new user_booking().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBooking_Button;
    private javax.swing.JButton DB;
    private javax.swing.JButton LeaveFeedback_Button;
    private javax.swing.JButton Logoutbutton;
    private javax.swing.JButton MyBookingButton;
    private javax.swing.JButton Profilebutton;
    private javax.swing.JButton Vehicles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
